mon = peripheral.wrap("top")
mon.clear()
mon.setTextScale(0.9)
mon.setCursorPos(1,1)
mon.write("Class ")
mon.setCursorPos(1,2)
mon.write("OHLE: ")
mon.setCursorPos(1,3)
mon.write("3rd/4th Rail: ")
mon.setCursorPos(1,4)
mon.write("Diesel: ")
mon.setCursorPos(1,5)
mon.write("Other power: ")
mon.setCursorPos(1,6)
mon.write("Livery: ")
mon.setCursorPos(1,7)
mon.write("Builders: ")
mon.setCursorPos(1,8)
mon.write("Other credits: ")